package:
  name: dpyr
  version: {{ environ.get('GIT_DESCRIBE_TAG', '') }}

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  {% if environ.get('GIT_DESCRIBE_NUMBER', '0') == '0' %}string: py{{ environ.get('PY_VER').replace('.', '') }}_0
  {% else %}string: py{{ environ.get('PY_VER').replace('.', '') }}_{{ environ.get('GIT_BUILD_STR', 'GIT_STUB') }}{% endif %}

source:
  path: ..

requirements:
  build:
    - ibis-framework >=0.10
    - numpy >=1.7.0
    - pandas >=0.12.0
    - python
    - setuptools
    - toolz
    - typing  # [py34]
  run:
    - ibis-framework >=0.10
    - numpy >=1.7.0
    - pandas >=0.12.0
    - python
    - setuptools
    - toolz
    - typing  # [py34]

test:
  requires:
    - graphviz
    - multipledispatch
    - pytest >=3
    - python-graphviz
  imports:
    - dpyr
  commands:
    - pytest --tb=short --pyargs dpyr

about:
  license: MIT
  summary: 'dplyr operations for Pandas and SQL databases in Python'
